<?php 
return[
    ''=>'controllers/index.php',
    'about'=>'controllers/about.php',
    'asociados'=>'controllers/asociados.php',
    'blog'=>'controllers/blog.php',
    'contact'=>'controllers/contact.php',
    'galeria'=>'controllers/galeria.php',
    'index'=>'controllers/index.php',
    'pruebaSql'=>'controllers/pruebaSQL.php',
    'single_post'=>'controllers/single_post.php',
];